#!/bin/bash

# local-vars: script to demonstrate local variables

foo=0	#Global

funct_1 () {

	local foo # local variable foo to funct_1
	foo=1
	echo "funct_1: foo = $foo"
}

funct_2 () {
	
	local foo # local variable foo to funct_2
	foo=2
	echo "funct_2: foo = $foo"
}

echo "global: foo = $foo"
funct_1
echo "global: foo = $foo"
funct_2
echo "global: foo = $foo"





